### ISSUE TITLE
Cancelling build leads to verified -1

### ISSUE THREAD

**Issue by macbutch** [jyrkiput/Hudson-Gerrit-Plugin#3]
Hi again,

This isn't exactly a bug but I've noticed that if I cancel a build then it will be marked as verified -1. What I'd really like is if it would just pretend that the build had never been started so that it can test that build again. Actually, a better idea might be if it added a comment to gerrit that doesn't affect the score that says 'build cancel - will test again later'...

Just ideas - it isn't a huge issue for us but we do have to upload a new change to trigger a new build which feels a little too manual.

-mark

**Comment by jyrkiput** [comment]
Hi,

Sorry that this took a while, I didn't notice this request :( But now this is done and I'll release a new version.
